#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091,SC2154
source /scripts/common

"${s6wrap[@]}" echo "[INFO] Starting VesselAlert version $(cat /.CONTAINER_VERSION)"
"${s6wrap[@]}" echo "[INFO] Notification Language is ${LANGUAGE:-en_US}"

# Put databases in place but don't overwrite any existing ones as they may have been changed by the user
mkdir -p /data/imagecache/screenshots/
cp -u --backup=numbered /opt/data/* /data >/dev/null 2>&1
if [[ -f /data/discord.error.log ]]
then
	tail -500 /data/discord.error.log > /tmp/discord.error.log
	mv -f /tmp/discord.error.log /data/discord.error.log
fi
rm -f "/run/vesseldb.lock"
