#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091,SC2154
source /scripts/common

"${s6wrap[@]}" echo "[INFO] Starting VesselAlert version $(cat /.CONTAINER_VERSION)"
"${s6wrap[@]}" echo "[INFO] Notification Language is ${LANGUAGE:-en_US}"

# Put databases in place but don't overwrite any existing ones as they may have been changed by the user
mkdir -p /data/imagecache/screenshots/
cp -u --backup=numbered /opt/data/* /data >/dev/null 2>&1 || true
if [[ -f /data/discord.error.log ]]; then
	tail -500 /data/discord.error.log > /tmp/discord.error.log
	mv -f /tmp/discord.error.log /data/discord.error.log || true
fi
rm -f "/run/vesseldb.lock"

# one-time move in case the user just upgraded from an older (pre-22-Mar-2025) container version
if [[ -f /data/container_has_run_before ]]; then mv -f /data/container_has_run_before /data/.container_has_run_before; fi
