#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091,SC2154

# Check to make sure the correct parameters are defined.
#---------------------------------------------------------------------------------------------
# Copyright (C) 2022-2025, Ramon F. Kolb (kx1t)
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#---------------------------------------------------------------------------------------------

source /scripts/common

"${s6wrap[@]}" echo "[INFO] Started as an s6 init script"

AIS_URL="${AIS_URL,,}"
if [[ "${AIS_URL:0:4}" != "http" ]]
then
    if [[ -z "$AIS_URL" ]]; then
        "${s6wrap[@]}" echo -n "[FATAL] AIS_URL is empty; "
    else 
        "${s6wrap[@]}" echo -n "[FATAL]  AIS_URL is set to \":$AIS_URL\"; expecting a URL starting with \"http://\" or \"https://\"."
    fi
    "${s6wrap[@]}" echo "[FATAL] Please correct and restart the container. Container execution is HALTED."
    exec sleep infinity & wait $!
fi
