#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091
source /scripts/common
s6wrap=(s6wrap --quiet --timestamps --prepend="$(basename "$0")" --args)

if ! chk_enabled "${TROPOALERT:-enabled}"; then
    "${s6wrap[@]}" echo "[INFO] TropoAlert is not enabled; if you want to notify when ships are received at long distance, then start container with TROPOALERT=true"
else
    "${s6wrap[@]}" echo "[INFO] TropoAlert enabled. Checking for Tropo every ${TROPOALERT_INTERVAL:-10m}. Minimum notification distance: ${TROPO_MINDIST:-100}nm."
fi
