#!/command/with-contenv bash
#shellcheck shell=bash
#shellcheck disable=SC1090,SC2015,SC1091,SC2302,SC2303

# AIS-Collect:
# read AIS data from a AIS-Catcher web service and
# create and maintain a database with this data
#---------------------------------------------------------------------------------------------
# Copyright (C) 2022-2025, Ramon F. Kolb (kx1t)
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#---------------------------------------------------------------------------------------------

source /scripts/common
[[ -z "${VESSELDBFILE}" ]] && VESSELDBFILE="/data/vessel.db" || true
[[ -z "${VESSELDBLOCK}" ]] && VESSELDBLOCK="/run/vesseldb.lock" || true

if [[ -z "$1" ]]
then
	echo "Usage: $0 mmsi"
	exit 1
fi

[[ -f  $VESSELDBLOCK ]] && echo "[$(date)][$APPNAME] Waiting for vessel.db to become unlocked..."
while [[ -f  $VESSELDBLOCK ]]
do
	sleep "0.$((RANDOM % 100))"
done

# Now lock the process for myself:
touch "$VESSELDBLOCK"

source "$VESSELDBFILE"
for key in "${KEY_INDEX[@]}"
do
	echo "Removing $1:$key"
	unset "VESSELS[$1:$key]"
done

for key in "${VESSEL_INDEX[@]}"
do
	[[ "$key" == "$1" ]] && echo "Removing VESSEL_INDEX[$key]=${VESSEL_INDEX[$key]}" || true
	unset "VESSEL_INDEX[$key]"
done

# write back to file
# shellcheck disable=SC1091
source "/usr/share/vesselalert/save_databases"

rm -f "$VESSELDBLOCK"
