#!/usr/bin/with-contenv bash
#shellcheck shell=bash
#shellcheck disable=SC2015,SC1090,SC2164,SC2001,SC1091


# Mastodon-Notifier
# Send notification to Mastodon
#---------------------------------------------------------------------------------------------
# Copyright (C) 2022-2023, Ramon F. Kolb (kx1t)
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#---------------------------------------------------------------------------------------------

# redirect stderr to stdout so it's picked up in the docker logs
exec 2>&1
# all errors will show a line number and the command used to produce the error
SCRIPT_PATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd)/$(basename "$0")"
trap 'echo -e "[$(date)][$APPNAME][ERROR] $SCRIPT_PATH in line $LINENO when executing: $BASH_COMMAND returned ${?}"' ERR

APPNAME="$(hostname)/notifier-framework"
echo "[$(date)][$APPNAME] Started as an s6 service"

renice -n 10 -p $$ >/dev/null 2>&1

[[ -z "${CHECK_INTERVAL}" ]] && CHECK_INTERVAL=30 || true
[[ -z "${VESSELDBFILE}" ]] && VESSELDBFILE="/data/vessel.db" || true
[[ -z "${VESSELDBLOCK}" ]] && VESSELDBLOCK="/run/vesseldb.lock" || true

notification_count=0

# [[ -n "$DEBUG" ]] && MASTODON_POST_VISIBILITY="private"
IMAGECACHE="${VESSELDBFILE%/*}/imagecache"
[[ -z "${MIN_MSG_COUNT}" ]] && MIN_MSG_COUNT=10 || true
if [[ -z "$MASTODON_MIN_DIST" ]] || [[ "$MASTODON_MIN_DIST" == "0" ]]
then
    unset MASTODON_MIN_DIST
fi

touch "$VESSELDBFILE"
rm -f "$VESSELDBLOCK"

mkdir -p "${IMAGECACHE}/screenshots"

# add some random time to the check interval (0-5 secs)
CHECK_INTERVAL="$(nice -n 20 bc -l <<<"scale=0; x=$RANDOM % 50; scale=1; $CHECK_INTERVAL + x/10")"

# Wait a cycle -- this gives AIS-Collect the chance to do at least an initial run:
sleep "$CHECK_INTERVAL"

# ---------------------------------------------------------------------------------------

while true
do

    # 3 main arrays:
    # - VESSELDICT is an associative array that contains all the vessels, indexed by their MMSI.
    #   So: ${!VESSELDICT[@]} contains the list of MMSIs, and ${VESSELDICT[$mmsi]}
    #   contains a comma-separated list of parameter values.
    #
    # - vesselinfo is an associative array that contains the information of a single vessel from
    #   the VESSELDICT array. The ${headers[@]} array contains the keys for each of these values.
    #
    # - mast_status is extracted from the right-most "notif_x" field from vesselinfo that starts with "mast="
    #   This array contains information about previous notifications to Mastodon for this MMSI

    # If there's a lock file, wait until it's gone\
    while [[ -f  $VESSELDBLOCK ]]
    do
        sleep 1
    done

    # Now lock the process for myself:
    touch "$VESSELDBLOCK"

    # First read the existing entries in from file
    [[ -n "$DEBUG" ]] && echo reading shipdict from file || true
    source "$VESSELDBFILE"

    # Iterate through the ships:
    for vessel in "${VESSEL_INDEX[@]}"
    do

        [[ -z "${VESSELS[${vessel}:mmsi]}" ]] && continue || true    # capture empty mmsi and skip
        # now we have the mastodon notification status of the vessel in mast_status. Let's check if we need to notify:

        # based on timing:
        if     [[ -n "$MASTODON_NOTIFY_EVERY" ]] \
        && [[ -n "${VESSELS[${vessel}:notification:last]}" ]] \
        && (( $(date +%s) <= ${VESSELS[${vessel}:notification:last]} + MASTODON_NOTIFY_EVERY ))
        then
            [[ -n "$DEBUG" ]] && echo "${VESSELS[${vessel}:mmsi]} (${VESSELS[${vessel}:shipname]}) skipped notify based on timing. (Last notification was $(( $(date +%s) - ${VESSELS[${vessel}:notification:last]} )) secs ago, minimum interval is $MASTODON_NOTIFY_EVERY secs )"
            notify_timing="false"
        else
            [[ -n "$DEBUG" ]] && echo "${VESSELS[${vessel}:mmsi]} (${VESSELS[${vessel}:shipname]}) ready to notify based on timing (or MASTODON_NOTIFY_EVERY is off). (Last notification was $( [[ -n "${VESSELS[${vessel}:notification:last]}" ]] && echo "$(( $(date +%s) - ${VESSELS[${vessel}:notification:last]} )) secs ago" || echo "never"), minimum interval is $MASTODON_NOTIFY_EVERY secs )"
            export notify_timing="true"
        fi
        # Never notify if last observation was more than 10 mins ago:
        if [[ -n "${VESSELS[${vessel}:last_signal]}" ]] \
        && (( ${VESSELS[${vessel}:last_signal]} > 600 ))
        then
            [[ -n "$DEBUG" ]] && echo "${VESSELS[${vessel}:mmsi]} (${VESSELS[${vessel}:shipname]}) overruled notify based on timing. (Last time heard was ${VESSELS[${vessel}:last_signal]} > 600 secs )"
            notify_timing="false"
        fi

        # based on distance from last notification:
        #shellcheck disable=SC2086
        if     [[ -n "${MASTODON_MIN_DIST}" ]] \
        && [[ -n "${VESSELS[${vessel}:lat]}" ]] && [[ -n "${VESSELS[${vessel}:lon]}" ]] \
        && [[ "${VESSELS[${vessel}:lat]}" != "null" ]] && [[ "${VESSELS[${vessel}:lon]}" != "null" ]] \
        && [[ -n "${VESSELS[${vessel}:notification:lat]}" ]] && [[ -n "${VESSELS[${vessel}:notification:lon]}" ]] \
        && [[ "$(nice -n 20 bc -l <<<"scale=2; $(nice -n 20 distance ${VESSELS[${vessel}:notification:lat]} ${VESSELS[${vessel}:notification:lon]} ${VESSELS[${vessel}:lat]} ${VESSELS[${vessel}:lon]}) <= $MASTODON_MIN_DIST")" == "1" ]]
        then
            notify_distance="false"
            [[ -n "$DEBUG" ]] && echo "${VESSELS[${vessel}:mmsi]} (${VESSELS[${vessel}:shipname]}) traveled distance too short - do not notify (measured $(nice -n 20 distance "${VESSELS[${vessel}:notification:lat]}" "${VESSELS[${vessel}:notification:lon]}" "${VESSELS[${vessel}:lat]}" "${VESSELS[${vessel}:lon]}") < allowed $MASTODON_MIN_DIST )"
        elif [[ -n "${MASTODON_MIN_DIST}" ]] \
        && [[ -n "${VESSELS[${vessel}:lat]}" ]] && [[ -n "${VESSELS[${vessel}:lon]}" ]] \
        && [[ "${VESSELS[${vessel}:lat]}" != "null" ]] && [[ "${VESSELS[${vessel}:lon]}" != "null" ]] \
        && [[ -n "${VESSELS[${vessel}:notification:lat]}" ]] && [[ -n "${VESSELS[${vessel}:notification:lon]}" ]]
        then
            export notify_distance="true"
            [[ -n "$DEBUG" ]] && [[ -n "${MASTODON_MIN_DIST}" ]] && echo "${VESSELS[${vessel}:mmsi]} (${VESSELS[${vessel}:shipname]}) ready to notify by distance: traveled distance far enough (measured $(nice -n 20 distance "${VESSELS[${vessel}:notification:lat]}" "${VESSELS[${vessel}:notification:lon]}" "${VESSELS[${vessel}:lat]}" "${VESSELS[${vessel}:lon]}") >= allowed $MASTODON_MIN_DIST )"
        else
            notify_distance="false"
            [[ -n "$DEBUG" ]] && [[ -z "${MASTODON_MIN_DIST}" ]] && echo "${VESSELS[${vessel}:mmsi]} (${VESSELS[${vessel}:shipname]}) no need to notify by distance: MASTODON_MIN_DIST not defined"
        fi

        # dont notify if it matches the Skip Filter
        if     [[ -n "${MASTODON_SKIP_FILTER}" ]] \
        && [[ ${VESSELS[${vessel}:mmsi]} =~ ${MASTODON_SKIP_FILTER} ]]
        then
            notify_filter="false"
            [[ -n "$DEBUG" ]] && echo "${VESSELS[${vessel}:mmsi]} (${VESSELS[${vessel}:shipname]}) skipped because of mmsi filter match (${MASTODON_SKIP_FILTER})"
        elif [[ -n "${MASTODON_SKIP_FILTER}" ]]
        then
            notify_filter="true"
            [[ -n "$DEBUG" ]] && echo "${VESSELS[${vessel}:mmsi]} (${VESSELS[${vessel}:shipname]}) ready to notify: MASTODON_SKIP_FILTER defined but no mmsi skip filter match"
        else
            notify_filter="true"
            [[ -n "$DEBUG" ]] && echo "${VESSELS[${vessel}:mmsi]} (${VESSELS[${vessel}:shipname]}) no need to notify by filter: no MASTODON_SKIP_FILTER defined"
        fi

        # check once more the min_msg_count. Too few messages means the screenshot won't be complete and it'd be better to wait
        if [[ ! ${VESSELS[${vessel}:count]}  =~ ^[0-9]+$ ]] || (( ${VESSELS[${vessel}:count]} < MIN_MSG_COUNT ))
        then
            notify_count="false"
            [[ -n "$DEBUG" ]] && echo "${VESSELS[${vessel}:mmsi]} (${VESSELS[${vessel}:shipname]}) Skipped notification: MIN_MSG_COUNT of $MIN_MSG_COUNT not yet exceeded (count=${VESSELS[${vessel}:count]})"
        else
            notify_count="true"
            [[ -n "$DEBUG" ]] && echo "${VESSELS[${vessel}:mmsi]} (${VESSELS[${vessel}:shipname]}) ready to notify: MIN_MSG_COUNT of $MIN_MSG_COUNT exceeded (count=${VESSELS[${vessel}:count]})"

        fi

        # Notification logic here for clarity:
        unset notify_now
        [[ "$notify_timing" == "true" ]] && notify_now="true"   # notify when timing is right or when the timing is undefined
        [[ "$notify_distance" == "true" ]] && notify_now="true" # notify when the distance traveled is far enough
        [[ "$notify_filter" == "false" ]] && unset notify_now   # stop and overrule notification if the MMSI filter has a match
        [[ "$notify_count" == "false" ]] && unset notify_now	# overrule notification because there are too few messages

        [[ -n "$DEBUG" ]] && [[ -n "$notify_now" ]] && echo "${VESSELS[${vessel}:mmsi]} (${VESSELS[${vessel}:shipname]}) Final result: Will do a Mastodon notification (timing=$notify_timing; distance=$notify_distance; filter=$notify_filter; count=$notify_count)"
        [[ -n "$DEBUG" ]] && [[ -z "$notify_now" ]] && echo "${VESSELS[${vessel}:mmsi]} (${VESSELS[${vessel}:shipname]}) Final result: Will not do a Mastodon notification (timing=$notify_timing; distance=$notify_distance; filter=$notify_filter; count=$notify_count)"

        if [[ -n "$notify_now" ]]
        then
            # we need to notify

            # Get a vessel image:
            image_link="https://photos.marinetraffic.com/ais/showphoto.aspx?mmsi=${VESSELS[${vessel}:mmsi]}"

            # Try to get an image if there isn't already one:
            if [[ ! -f "$IMAGECACHE/${VESSELS[${vessel}:mmsi]}.jpg" ]]
            then
                if ! curl -sL -A "Mozilla/5.0 (X11; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0" "$image_link" -o  "$IMAGECACHE/${VESSELS[${vessel}:mmsi]}.jpg"
                then
                    rm -f "$IMAGECACHE/${VESSELS[${vessel}:mmsi]}.jpg"
                fi
            fi
            # If the file starts with <!DOCTYPE html>, we know it was an error message and we can erase it:
            if grep '<!DOCTYPE html>' < <(dd bs=1 count=15 if="$IMAGECACHE/${VESSELS[${vessel}:mmsi]}.jpg" 2>/dev/null) >/dev/null 2>&1
            then
                rm -f "$IMAGECACHE/${VESSELS[${vessel}:mmsi]}.jpg"
            fi

            # Try to get a screenshot:
            rm -f "/${IMAGECACHE}/screenshots/${VESSELS[${vessel}:mmsi]}.jpg"

            # get a screenshot
            if [[ -n "$SCREENSHOT_URL" ]] && curl -sSL "$SCREENSHOT_URL/snap/${VESSELS[${vessel}:mmsi]}" -o "${IMAGECACHE}/screenshots/${VESSELS[${vessel}:mmsi]}.jpg"
            then
                echo "[$(date)][$APPNAME] Got screenshot for ${VESSELS[${vessel}:mmsi]} (${VESSELS[${vessel}:shipname]})"
            else
                echo "[$(date)][$APPNAME] Failed to get screenshot for ${VESSELS[${vessel}:mmsi]} (${VESSELS[${vessel}:shipname]})"
            fi

            # ---------------------------------------------------------------------------------------------
            # INSERT ANY CALLS TO ACTUAL NOTIFIERS BETWEEN THE TWO LINES
            [[ -n "${MASTODON_ACCESS_TOKEN}" ]] && nice -n 20 /usr/share/vesselalert/send_mastodon "${VESSELS[${vessel}:mmsi]}"
            [[ -n "${DISCORD_WEBHOOKS}" ]] && nice -n 20 /usr/share/vesselalert/send_discord "${VESSELS[${vessel}:mmsi]}"

            # ---------------------------------------------------------------------------------------------

            # Update the Assoc Array with the latest values:
            # update mast_status values:
            VESSELS[${vessel}:notification:lat]="${VESSELS[${vessel}:lat]}"
            VESSELS[${vessel}:notification:lon]="${VESSELS[${vessel}:lon]}"
            VESSELS[${vessel}:notification:last]="$(date +%s)"

            [[ -n "$DEBUG" ]] && echo "updated VESSELS[$mmsi]"
            # Increment notification count
            (( notification_count++ )) || true

            if [[ -n "$NOTIFICATION_THROTTLE" ]] && [[ "$(nice -n 20 bc <<< "${notification_count}%10")" == "0" ]]
            then
                # we need to throttle - let's wait 15 seconds
                [[ -n "$DEBUG" ]] && echo "Notification Count is ${notification_count}; throttling for 15 seconds"
                sleep 15
            fi
        fi
    done

    [[ -n "$DEBUG" ]] && echo "Notification count: ${notification_count}"

    # Write arrays back to the file if it was changed:
    if (( notification_count > 0 ))
    then
        # Write back to file
        source /usr/share/vesselalert/save_databases
        notification_count=0
    fi

    # Remove file block:
    rm -f "$VESSELDBLOCK"

    # Sleep a bit
    sleep "$CHECK_INTERVAL"

done
