#!/command/with-contenv bash
#shellcheck shell=bash disable=SC2015
#---------------------------------------------------------------------------------------------
# Copyright (C) 2022-2023, Ramon F. Kolb (kx1t)
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#---------------------------------------------------------------------------------------------

# This script is sourced from several services to make sure that all of the persistent arrays are stored

[[ -z "${VESSELDBFILE}" ]] && VESSELDBFILE="/data/vessel.db" || true

{
    declare -p KEY_INDEX
    declare -p VESSEL_INDEX
    declare -p VESSELS
    declare -p SHIPTYPE
    declare -p SHIPSTATUS
    declare -p COUNTRY ;} > "$VESSELDBFILE" 2>/dev/null

[[ -n "$DEBUG" ]] && echo "wrote back to file" || true
