#!/command/with-contenv bash
#shellcheck shell=bash disable=SC2015,SC2154,SC1091
#---------------------------------------------------------------------------------------------
# Copyright (C) 2022-2025, Ramon F. Kolb (kx1t)
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#---------------------------------------------------------------------------------------------

# This script is sourced from several services to make sure that all of the persistent arrays are stored

source /scripts/common

[[ -z "${VESSELDBFILE}" ]] && VESSELDBFILE="/data/vessel.db" || true

{   declare -p KEY_INDEX 2>/dev/null || true
    declare -p VESSEL_INDEX 2>/dev/null || true
    declare -p VESSELS 2>/dev/null || true
    declare -p SHIPTYPE 2>/dev/null || true
    declare -p SHIPSTATUS 2>/dev/null || true
    declare -p COUNTRY 2>/dev/null || true
} > "$VESSELDBFILE" 2>/dev/null || true

[[ -n "$DEBUG" ]] && "${s6wrap[@]}" echo "wrote back to file" || true
