#!/usr/bin/with-contenv bash
#shellcheck shell=bash

# AIS-Collect:
# read AIS data from a AIS-Catcher web service and
# create and maintain a CSV database with this data
#---------------------------------------------------------------------------------------------
# Copyright (C) 2022-2023, Ramon F. Kolb (kx1t)
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#---------------------------------------------------------------------------------------------

# redirect stderr to stdout so it's picked up in the docker logs
exec 2>&1
# all errors will show a line number and the command used to produce the error
#shellcheck disable=SC2164
SCRIPT_PATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd)/$(basename "$0")"
trap 'echo -e "[$(date)][$APPNAME][ERROR] $SCRIPT_PATH in line $LINENO when executing: $BASH_COMMAND returned ${?}"' ERR

APPNAME="$(hostname)/cleanup"
echo "[$(date)][$APPNAME] Started as an s6 service"

renice -n 20 -p $$ >/dev/null 2>/dev/null

CLEANUP_EVERY=3600			# every 1 hour
PHOTOS_RETENTION=10080 		# time in minutes; 10080 = 1 week
SCREENSHOT_RETENTION=3600	# 1 hour

while true
do
	echo "[$(date)][$APPNAME] Cleanup performed"
	find /data/imagecache/screenshots -maxdepth 1 -mmin +${SCREENSHOT_RETENTION} -type f -iname "*.jpg" -delete >/dev/null 2>&1
	find /data/imagecache             -maxdepth 1 -mmin +${PHOTOS_RETENTION}     -type f -iname "*.jpg" -delete >/dev/null 2>&1

	sleep "${CLEANUP_EVERY}"
done
