#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Check to make sure the correct parameters are defined.
#---------------------------------------------------------------------------------------------
# Copyright (C) 2022-2023, Ramon F. Kolb (kx1t)
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#---------------------------------------------------------------------------------------------


APPNAME="$(hostname)/40-check-ais-notify"
echo "[$(date)][$APPNAME] Started as an s6 init script"

AIS_URL="${AIS_URL,,}"
if [[ "${AIS_URL:0:4}" != "http" ]]
then
    [[ -z "$AIS_URL" ]] && echo -n "WARNING: AIS_URL is empty; " || echo -n "WARNING: AIS_URL is set to \":$AIS_URL\"; "
    echo "expecting a URL starting with \"http://\" or \"https://\"."
    echo "[$(date)][$APPNAME]         Please correct and restart the container."
    echo "[$(date)][$APPNAME] Container execution is HALTED."
    sleep infinity
fi
