#!/usr/bin/with-contenv bash
#shellcheck shell=bash disable=SC2015,SC1091

APPNAME="$(hostname)/60-check-mastodon"
#---------------------------------------------------------------------------------------------
# Copyright (C) 2022-2023, Ramon F. Kolb (kx1t)
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#---------------------------------------------------------------------------------------------


echo "[$(date)][$APPNAME] Checking Mastodon server and access token"

if [[ -z "$MASTODON_ACCESS_TOKEN" ]] || [[ -z "$MASTODON_SERVER" ]]
then
    echo "[$(date)][$APPNAME] Mastodon not configured"
else
    MASTODON_SERVER="${MASTODON_SERVER,,}"
    # strip http:// https://
    [[ "${MASTODON_SERVER:0:7}" == "http://" ]] && MASTODON_SERVER="${MASTODON_SERVER:7}" || true
    [[ "${MASTODON_SERVER:0:8}" == "https://" ]] && MASTODON_SERVER="${MASTODON_SERVER:8}" || true
    result="$(curl -sS -H "Authorization: Bearer $MASTODON_ACCESS_TOKEN" "https://${MASTODON_SERVER}/api/v1/apps/verify_credentials")"
    if  grep -vi "The access token is invalid"  <<< "$result" >/dev/null 2>&1
    then
        echo "[$(date)][$APPNAME] Mastodon configured correctly for application $(jq '.name' <<< "$result") / website $(jq '.website' <<< "$result")"
    else
        echo "[$(date)][$APPNAME] Mastodon configured incorrectly. Check your setup"
    fi
fi
