#!/usr/bin/with-contenv bash
#shellcheck shell=bash disable=SC2015,SC1091,SC1090

APPNAME="$(hostname)/70-set-strings"
#---------------------------------------------------------------------------------------------
# Copyright (C) 2022-2023, Ramon F. Kolb (kx1t)
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
#---------------------------------------------------------------------------------------------

echo "[$(date)][$APPNAME] Loading Vessel and Status Descriptions"

[[ -z "${VESSELDBFILE}" ]] && VESSELDBFILE="/data/vessel.db" || true

# First read the existing entries in from file
if (( $(wc -l < "$VESSELDBFILE") > 0 ))
then
    [[ -n "$DEBUG" ]] && echo reading VESSELS dict from file || true
    source "$VESSELDBFILE"
fi

# Both for SHIPTYPE and SHIPSTATUS -- comment out those values that you do not want to see appear in notifications
# This is mostly for "Not Available", "Reserved", etc.
unset SHIPTYPE
declare -A SHIPTYPE

if [[ -f /data/shiptype.db ]]
then
    source "/data/shiptype.db"
else
    #SHIPTYPE[0]="Not Available"
    #SHIPTYPE[1]="Reserved for future use"
    #SHIPTYPE[2]="Reserved for future use"
    #SHIPTYPE[3]="Reserved for future use"
    #SHIPTYPE[4]="Reserved for future use"
    #SHIPTYPE[5]="Reserved for future use"
    #SHIPTYPE[6]="Reserved for future use"
    #SHIPTYPE[7]="Reserved for future use"
    #SHIPTYPE[8]="Reserved for future use"
    #SHIPTYPE[9]="Reserved for future use"
    #SHIPTYPE[10]="Reserved for future use"
    #SHIPTYPE[11]="Reserved for future use"
    #SHIPTYPE[12]="Reserved for future use"
    #SHIPTYPE[13]="Reserved for future use"
    #SHIPTYPE[14]="Reserved for future use"
    #SHIPTYPE[15]="Reserved for future use"
    #SHIPTYPE[16]="Reserved for future use"
    #SHIPTYPE[17]="Reserved for future use"
    #SHIPTYPE[18]="Reserved for future use"
    #SHIPTYPE[19]="Reserved for future use"
    SHIPTYPE[20]="#WIG (Wing in ground)"
    SHIPTYPE[21]="#WIG #Hazard cat A"
    SHIPTYPE[22]="#WIG #Hazard cat B"
    SHIPTYPE[23]="#WIG #Hazard cat B"
    SHIPTYPE[24]="#WIG #Hazard cat D"
    SHIPTYPE[25]="#WIG"
    SHIPTYPE[26]="#WIG"
    SHIPTYPE[27]="#WIG"
    SHIPTYPE[28]="#WIG"
    SHIPTYPE[29]="#WIG"
    SHIPTYPE[30]="#Fishing"
    SHIPTYPE[31]="#Towing"
    SHIPTYPE[32]="#Towing (Large)"
    SHIPTYPE[33]="#Dredging"
    SHIPTYPE[34]="#Diving"
    SHIPTYPE[35]="#Military #Mil #Navy"
    SHIPTYPE[36]="#Sailing"
    SHIPTYPE[37]="#Pleasure Craft"
    #SHIPTYPE[38]="Reserved"
    #SHIPTYPE[39]="Reserved"
    SHIPTYPE[40]="#HiSpeed"
    SHIPTYPE[41]="#HiSpeed #Hazard cat A"
    SHIPTYPE[42]="#HiSpeed #Hazard cat B"
    SHIPTYPE[43]="#HiSpeed #Hazard cat C"
    SHIPTYPE[44]="#HiSpeed #Hazard cat D"
    #SHIPTYPE[45]="#HiSpeed Reserved"
    #SHIPTYPE[46]="#HiSpeed Reserved"
    #SHIPTYPE[47]="#HiSpeed Reserved"
    #SHIPTYPE[48]="#HiSpeed Reserved"
    SHIPTYPE[49]="#HiSpeed"
    SHIPTYPE[50]="#Pilot vessel"
    SHIPTYPE[51]="#SAR"
    SHIPTYPE[52]="#Tug"
    SHIPTYPE[53]="#Port_Tender"
    SHIPTYPE[54]="#Anti_Pollution"
    SHIPTYPE[55]="#Law #Enforcement"
    SHIPTYPE[56]="#Local"
    SHIPTYPE[57]="#Local"
    SHIPTYPE[58]="#Medical transport"
    SHIPTYPE[59]="#Non_Combatant #Mil #Navy"
    SHIPTYPE[60]="#Passenger"
    SHIPTYPE[61]="#Passenger  #Hazard cat A"
    SHIPTYPE[62]="#Passenger  #Hazard cat B"
    SHIPTYPE[63]="#Passenger  #Hazard cat C"
    SHIPTYPE[64]="#Passenger  #Hazard cat D"
    #SHIPTYPE[65]="#Passenger Reserved"
    #SHIPTYPE[66]="#Passenger Reserved"
    #SHIPTYPE[67]="#Passenger Reserved"
    #SHIPTYPE[68]="#Passenger Reserved"
    SHIPTYPE[69]="#Passenger"
    SHIPTYPE[70]="#Cargo"
    SHIPTYPE[71]="#Cargo #Hazard cat A"
    SHIPTYPE[72]="#Cargo #Hazard cat B"
    SHIPTYPE[73]="#Cargo #Hazard cat C"
    SHIPTYPE[74]="#Cargo #Hazard cat D"
    #SHIPTYPE[75]="#Cargo Reserved"
    #SHIPTYPE[76]="#Cargo Reserved"
    #SHIPTYPE[77]="#Cargo Reserved"
    #SHIPTYPE[78]="#Cargo Reserved"
    SHIPTYPE[79]="#Cargo"
    SHIPTYPE[80]="#Tanker"
    SHIPTYPE[81]="#Tanker #Hazard cat A"
    SHIPTYPE[82]="#Tanker #Hazard cat B"
    SHIPTYPE[83]="#Tanker #Hazard cat C"
    SHIPTYPE[84]="#Tanker #Hazard cat D"
    #SHIPTYPE[85]="#Tanker Reserved"
    #SHIPTYPE[86]="#Tanker Reserved"
    #SHIPTYPE[87]="#Tanker Reserved"
    #SHIPTYPE[88]="#Tanker Reserved"
    SHIPTYPE[89]="#Tanker"
    SHIPTYPE[90]="#Other"
    SHIPTYPE[91]="#Other #Hazard cat A"
    SHIPTYPE[92]="#Other #Hazard cat B"
    SHIPTYPE[93]="#Other #Hazard cat C"
    SHIPTYPE[94]="#Other #Hazard cat D"
    #SHIPTYPE[95]="#Other Reserved"
    #SHIPTYPE[96]="#Other Reserved"
    #SHIPTYPE[97]="#Other Reserved"
    #SHIPTYPE[98]="#Other Reserved"
    SHIPTYPE[99]="#Other"
fi
unset SHIPSTATUS
declare -A SHIPSTATUS
if [[ -f /data/shipstatus.db ]]
then
    source "/data/shipstatus.db"
else
    SHIPSTATUS[0]="#under_way_using_engine"
    SHIPSTATUS[1]="#anchored"
    SHIPSTATUS[2]="#not_under_command "
    SHIPSTATUS[3]="#restricted_maneuverability"
    SHIPSTATUS[4]="#draught_constrained"
    SHIPSTATUS[5]="#moored"
    SHIPSTATUS[6]="#aground "
    SHIPSTATUS[7]="#fishing"
    SHIPSTATUS[8]="#under_way_sailing #sailing"
    # SHIPSTATUS[9]="reserved for future amendment of navigational status for ships carrying DG, HS, or MP, or IMO hazard or pollutant category C, high-speed craft (HSC)"
    # SHIPSTATUS[10]="reserved for future amendment of navigational status for ships carrying dangerous goods (DG), harmful substances (HS) or marine pollutants (MP), or IMO hazard or pollutant category A, wing in ground (WIG)"
    SHIPSTATUS[11]="#tow_pulling"
    SHIPSTATUS[12]="#tow_pushing"
    #SHIPSTATUS[13]="reserved for future use"
    SHIPSTATUS[14]="#AIS-SART #MOB-AIS #EPIRB-AIS"
    #SHIPSTATUS[15]="undefined = default (also used by AIS-SART, MOB-AIS and EPIRB-AIS under test)"
fi
# Make sure the other arrays have been declared if they don't already exist:
! declare -p VESSELS >/dev/null 2>&1 && declare -A VESSELS || true
! declare -p KEY_INDEX >/dev/null 2>&1 && declare -a KEY_INDEX || true
! declare -p VESSEL_INDEX >/dev/null 2>&1 && declare -a VESSEL_INDEX || true

# write back to file
{
    declare -p KEY_INDEX
    declare -p VESSEL_INDEX
    declare -p VESSELS
    declare -p SHIPTYPE
    declare -p SHIPSTATUS ;} > "$VESSELDBFILE"
